[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30.3"
env_logger = "0.11.3"
log = "0.4.22"
wgpu = "0.20.1"
tokio = { version = "1.38.0", features = ["full"] }
bytemuck = { version = "1.16.1", features = [ "derive" ] }